label: 'Termo de taxonomia'
display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Tudo -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      arguments:
        tid:
          exception:
            title: Tudo
  feed_1:
    display_title: Feed
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Tudo -'
            offset_label: Offset
  page_1:
    display_title: Página
