label: Conteúdo
description: 'Encontrar e gerenciar conteúdo.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
      fields:
        title:
          label: Título
        name:
          label: Autor
        status:
          label: Status
        changed:
          label: Atualizado
        operations:
          label: Operações
      filters:
        status:
          expose:
            label: Status
          group_info:
            group_items:
              1:
                title: Publicado
        type:
          expose:
            label: Tipo
        title:
          expose:
            label: Título
        langcode:
          expose:
            label: Idioma
      title: Conteúdo
      empty:
        area_text_custom:
          content: 'Sem conteúdo disponivel.'
    display_title: Principal
  page_1:
    display_options:
      menu:
        title: Conteúdo
      tab_options:
        title: Conteúdo
    display_title: Página
